
---------------
--
--Drop Table
CALL FNC.DROP_IF_EXISTS('SAILW1483V.DM_BLOOD_PRESSURES');
COMMIT;
------------------------------------------ 
--
-- Create Table
CREATE TABLE SAILW1483V.DM_BLOOD_PRESSURES
(
	ALF_PE			BIGINT, 
	EVENT_DT		DATE, 
	SYS				INTEGER, 
	DYS				INTEGER, 
	MEAN_BP			DECIMAL(31,8),
	PP				INTEGER,
	PP_INDEX		DECIMAL(31,8),
	SYS_CD			INTEGER, 
	DYS_CD			INTEGER 		
) 
;
COMMIT;
------------------------------------------
--
--Insert into Table
INSERT INTO SAILW1483V.DM_BLOOD_PRESSURES

WITH RELEVANT_CODES_BP AS 
(
SELECT 
READ_CODE, 
PREF_TERM_30, 
PREF_TERM_60, 
'BP' AS READ_TYPE 
FROM SAILUKHDV.READ_CD_CV2_SCD R

WHERE READ_CODE LIKE '246..'
)
,

ALL_BP_READINGS	AS 
(
SELECT 
RT.ALF_PE, 
RT.EVENT_CD, 
RT.EVENT_DT, 
RT.EVENT_VAL, 
LT.READ_TYPE 
FROM RELEVANT_CODES_BP LT

LEFT JOIN 
(
SELECT 
ALF_PE, 
EVENT_CD, 
EVENT_DT, 
EVENT_VAL 
FROM SAILW1483V.EXTRACT_P2_WLGP_GP_EVENT_CLEANSED
) AS RT
ON LT.READ_CODE = RT.EVENT_CD
)
,

BP_S1 AS 
(
SELECT 
UNIQUE ALF_PE, 
EVENT_DT 
FROM ALL_BP_READINGS
)
,

BP_S2 AS 
(
SELECT 
ALF_PE, 
INT(LEFT(EVENT_VAL, 3)) AS SYS1, 
INT(LEFT(EVENT_VAL, 2)) AS SYS2, 
INT(RIGHT(INT(EVENT_VAL), 3)) AS DYS, 
EVENT_DT, 
EVENT_VAL 
FROM 
(
SELECT 
* 
FROM ALL_BP_READINGS
)
) 
,
        
BP_S3 AS 
(
SELECT 
ALF_PE, 
EVENT_DT, 
EVENT_VAL, 
SYS2,
CASE 
    WHEN SYS1 BETWEEN 210 AND 600 OR SYS1 < 70 OR SYS1 <= DYS THEN NULL
    ELSE SYS1
END AS SYS1,
CASE 
    WHEN DYS > 160 OR DYS < 40 OR SYS1 <= DYS THEN NULL 
    ELSE DYS
END AS DYS
FROM BP_S2		
)        
,

BP_S4 AS 
(
SELECT 
* 
FROM 
(
SELECT 
*,
CASE 
    WHEN SYS2 > DYS THEN SYS2
    ELSE SYS1
END AS SYS_FINAL
FROM BP_S3
)
WHERE SYS_FINAL IS NOT NULL
)
,

BP_S5 AS 
(
SELECT 
ALF_PE, 
EVENT_DT, 
EVENT_VAL,
CASE 
    WHEN SYS_FINAL > 210 OR SYS_FINAL < 70 OR SYS_FINAL <= DYS OR SYS_FINAL > (DYS*3) THEN -999
    ELSE SYS_FINAL
END AS SYS,
CASE 
    WHEN DYS > 160 OR DYS < 40 OR SYS_FINAL <= DYS OR SYS_FINAL > (DYS*3) THEN -999 
    ELSE DYS
END AS DYS
FROM BP_S4	
)
,

BP_S6 AS
(
SELECT 
LT.ALF_PE, 
LT.EVENT_DT, 
RT.SYS, 
RT.DYS 
FROM BP_S1 LT

LEFT JOIN 
(
SELECT 
ALF_PE, 
EVENT_DT, 
SYS, 
DYS  
FROM 
(
SELECT 
ROW_NUMBER() OVER (PARTITION BY ALF_PE, EVENT_DT ORDER BY SYS) AS ROWNUM, 
* 
FROM BP_S5
) 
WHERE ROWNUM = 1
) AS RT
ON LT.ALF_PE = RT.ALF_PE
AND LT.EVENT_DT = RT.EVENT_DT
)
,

BP_S7 AS
(
SELECT 
*, 
ROUND((CAST(SYS AS DECIMAL(31,8)) + (2*DYS))/3,2) AS MEAN_BP,
SYS - DYS AS PP
FROM BP_S6
)

SELECT
*,
ROUND(PP / MEAN_BP,2) AS PP_INDEX,
CASE WHEN SYS = -999 THEN 9 ELSE 1 END AS SYS_CD, 
CASE WHEN DYS = -999 THEN 9 ELSE 1 END AS DYS_CD 
FROM BP_S7
;
----------------------------------
--
-- Select all results
SELECT 
	* 
FROM 
	SAILW1483V.DM_BLOOD_PRESSURES
ORDER BY ALF_PE
FETCH FIRST 100 ROWS ONLY;
--
-- Count all results
SELECT 
	COUNT(*)
FROM 
	SAILW1483V.DM_BLOOD_PRESSURES
;
--
-- Count distinct alfs
SELECT 
	COUNT(DISTINCT ALF_PE)
FROM 
	SAILW1483V.DM_BLOOD_PRESSURES
;
---------------------------------   
--
--Drop Table
CALL FNC.DROP_IF_EXISTS('SAILW1483V.ASCVD_BLOOD_PRESSURES');
COMMIT;
------------------------------------------ 
--
-- Create Table
CREATE TABLE SAILW1483V.ASCVD_BLOOD_PRESSURES
(
	ALF_PE			BIGINT, 
	EVENT_DT		DATE, 
	SYS				INTEGER, 
	DYS				INTEGER, 
	MEAN_BP			DECIMAL(31,8),
	PP				INTEGER,
	PP_INDEX		DECIMAL(31,8),
	SYS_CD			INTEGER, 
	DYS_CD			INTEGER 		
) 
;
COMMIT;
------------------------------------------
--
--Insert into Table
INSERT INTO SAILW1483V.ASCVD_BLOOD_PRESSURES

WITH RELEVANT_CODES_BP AS 
(
SELECT 
READ_CODE, 
PREF_TERM_30, 
PREF_TERM_60, 
'BP' AS READ_TYPE 
FROM SAILUKHDV.READ_CD_CV2_SCD R

WHERE READ_CODE LIKE '246..'
)
,

ALL_BP_READINGS	AS 
(
SELECT 
RT.ALF_PE, 
RT.EVENT_CD, 
RT.EVENT_DT, 
RT.EVENT_VAL, 
LT.READ_TYPE 
FROM RELEVANT_CODES_BP LT

LEFT JOIN 
(
SELECT 
ALF_PE, 
EVENT_CD, 
EVENT_DT, 
EVENT_VAL 
FROM SAILW1483V.EXTRACT_WLGP_GP_EVENT_CLEANSED
) AS RT
ON LT.READ_CODE = RT.EVENT_CD
)
,

BP_S1 AS 
(
SELECT 
UNIQUE ALF_PE, 
EVENT_DT 
FROM ALL_BP_READINGS
)
,

BP_S2 AS 
(
SELECT 
ALF_PE, 
INT(LEFT(EVENT_VAL, 3)) AS SYS1, 
INT(LEFT(EVENT_VAL, 2)) AS SYS2, 
INT(RIGHT(INT(EVENT_VAL), 3)) AS DYS, 
EVENT_DT, 
EVENT_VAL 
FROM 
(
SELECT 
* 
FROM ALL_BP_READINGS
)
) 
,
        
BP_S3 AS 
(
SELECT 
ALF_PE, 
EVENT_DT, 
EVENT_VAL, 
SYS2,
CASE 
    WHEN SYS1 BETWEEN 210 AND 600 OR SYS1 < 70 OR SYS1 <= DYS THEN NULL
    ELSE SYS1
END AS SYS1,
CASE 
    WHEN DYS > 160 OR DYS < 40 OR SYS1 <= DYS THEN NULL 
    ELSE DYS
END AS DYS
FROM BP_S2		
)        
,

BP_S4 AS 
(
SELECT 
* 
FROM 
(
SELECT 
*,
CASE 
    WHEN SYS2 > DYS THEN SYS2
    ELSE SYS1
END AS SYS_FINAL
FROM BP_S3
)
WHERE SYS_FINAL IS NOT NULL
)
,

BP_S5 AS 
(
SELECT 
ALF_PE, 
EVENT_DT, 
EVENT_VAL,
CASE 
    WHEN SYS_FINAL > 210 OR SYS_FINAL < 70 OR SYS_FINAL <= DYS OR SYS_FINAL > (DYS*3) THEN -999
    ELSE SYS_FINAL
END AS SYS,
CASE 
    WHEN DYS > 160 OR DYS < 40 OR SYS_FINAL <= DYS OR SYS_FINAL > (DYS*3) THEN -999 
    ELSE DYS
END AS DYS
FROM BP_S4	
)
,

BP_S6 AS
(
SELECT 
LT.ALF_PE, 
LT.EVENT_DT, 
RT.SYS, 
RT.DYS 
FROM BP_S1 LT

LEFT JOIN 
(
SELECT 
ALF_PE, 
EVENT_DT, 
SYS, 
DYS  
FROM 
(
SELECT 
ROW_NUMBER() OVER (PARTITION BY ALF_PE, EVENT_DT ORDER BY SYS) AS ROWNUM, 
* 
FROM BP_S5
) 
WHERE ROWNUM = 1
) AS RT
ON LT.ALF_PE = RT.ALF_PE
AND LT.EVENT_DT = RT.EVENT_DT
)
,

BP_S7 AS
(
SELECT 
*, 
ROUND((CAST(SYS AS DECIMAL(31,8)) + (2*DYS))/3,2) AS MEAN_BP,
SYS - DYS AS PP
FROM BP_S6
)

SELECT
*,
ROUND(PP / MEAN_BP,2) AS PP_INDEX,
CASE WHEN SYS = -999 THEN 9 ELSE 1 END AS SYS_CD, 
CASE WHEN DYS = -999 THEN 9 ELSE 1 END AS DYS_CD 
FROM BP_S7
;
----------------------------------
--
-- Select all results
SELECT 
	* 
FROM 
	SAILW1483V.ASCVD_BLOOD_PRESSURES
ORDER BY ALF_PE
FETCH FIRST 100 ROWS ONLY;
--
-- Count all results
SELECT 
	COUNT(*)
FROM 
	SAILW1483V.ASCVD_BLOOD_PRESSURES
;
--
-- Count distinct alfs
SELECT 
	COUNT(DISTINCT ALF_PE)
FROM 
	SAILW1483V.ASCVD_BLOOD_PRESSURES
;
---------------------------------             