------------------------------------------
--
--Drop Table
CALL FNC.DROP_IF_EXISTS('SAILW1483V.CAPSTONE_DM_RISK_CALCULATION');
COMMIT;
------------------------------------------ 
--
-- Create Table
CREATE TABLE SAILW1483V.CAPSTONE_DM_RISK_CALCULATION
(
	ALF_PE			BIGINT,
	DIAG_DT			DATE,
	CNS_DT			DATE,
	COHORT			VARCHAR(10),
	LSOA			VARCHAR(10),
	MSOA			VARCHAR(10),
	LAD				VARCHAR(10),
	HE				INTEGER,
	SEX				VARCHAR(1),
	WIMD			INTEGER,
	TOWNSEND		DECIMAL(31,8),
	ETHN			VARCHAR(10),
	AGE				INTEGER,
	TYPE			VARCHAR(10),
	SMK				VARCHAR(10),
	BMI				DECIMAL(31,8),
	DM				INTEGER,
	DMTA			INTEGER,
	LVR				INTEGER,
	HTN				INTEGER,
	HF				INTEGER,
	AF				INTEGER,
	RA				INTEGER,
	FH_CVD			INTEGER,
	CKD				INTEGER,
	LLT_INT			INTEGER,
	STATIN			INTEGER,	
	AHT_INT			INTEGER,
	AHT				INTEGER,	
	LDL				VARCHAR(10),
	LDL_VAL			DECIMAL(31,8),
	NHDL			VARCHAR(10),	
	NHDL_VAL		DECIMAL(31,8),
	TC_HDL			DECIMAL(31,8),	
	EGFR			VARCHAR(10),	
	EGFR_VAL		DECIMAL(31,8),
	SBP_VAL			DECIMAL(31,8)
) 
;
COMMIT;
------------------------------------------
--
--Insert into Table
INSERT INTO SAILW1483V.CAPSTONE_DM_RISK_CALCULATION
--
WITH ALFS AS
(
SELECT 
	ALF_PE,
	FIRST_DATE
FROM 
	SAILW1483V.P2_DIABETES_COHORT_MASTER M

WHERE YEAR(FIRST_DATE) IN(2022,2023)
)

--SELECT COUNT(DISTINCT ALF_PE) FROM ALFS
,

-- RHEUMATOID ARTHRITIS  
RA_WLGP AS (
    SELECT DISTINCT e.ALF_PE
    FROM SAILW1483V.EXTRACT_P2_WLGP_GP_EVENT_CLEANSED e
    INNER JOIN SAILW1483V.P2_DIABETES_COHORT_MASTER c ON e.ALF_PE = c.ALF_PE
    WHERE e.EVENT_CD IN (
        '66HB0',  -- RA monitoring
        'N040.',  -- Rheumatoid arthritis
        'N0402',  -- RA of shoulder
        'N0408',  -- RA of MCP joint
        'N0409',  -- RA of PIP joint of finger
        'N0405',  -- RA of elbow
        'N0400',  -- RA of cervical spine
        'N040D',  -- RA of knee
        'N040F',  -- RA of ankle
        'N04..',  -- RA and other inflammatory polyarthropathy
        'N0407',  -- RA of wrist
        'N040C',  -- RA of sacro-iliac joint
        'N0406',  -- RA of distal radio-ulnar joint
        'N040A',  -- RA of DIP joint of finger
        'N040B'   -- RA of hip
    )
    AND e.EVENT_DT < c.FIRST_DATE
),

RA_PEDW AS (
    SELECT DISTINCT S.ALF_PE
    FROM SAILW1483V.EXTRACT_P2_PEDW_SPELL S
    
JOIN SAILW1483V.EXTRACT_P2_PEDW_EPISODE E
	ON E.PROV_UNIT_CD = S.PROV_UNIT_CD 
	AND E.SPELL_NUM_PE = S.SPELL_NUM_PE

JOIN SAILW1483V.EXTRACT_P2_PEDW_DIAG D
	ON E.PROV_UNIT_CD = D.PROV_UNIT_CD
	AND E.SPELL_NUM_PE = D.SPELL_NUM_PE
	AND E.EPI_NUM = D.EPI_NUM	
 
INNER JOIN SAILW1483V.P2_DIABETES_COHORT_MASTER c ON S.ALF_PE = c.ALF_PE
    
WHERE D.DIAG_CD_1234 IN ('M069', 'M068', 'M061', 'M060', 'M064')
AND s.ADMIS_DT < c.FIRST_DATE
),

RA AS (
    SELECT ALF_PE FROM RA_WLGP
    UNION
    SELECT ALF_PE FROM RA_PEDW
)

--SELECT * FROM RA
,

--FAMILY HISTORY OF ANGINA / MI
FH_CVD AS (
    SELECT DISTINCT e.ALF_PE
    FROM SAILW1483V.EXTRACT_P2_WLGP_GP_EVENT_CLEANSED e
    INNER JOIN SAILW1483V.P2_DIABETES_COHORT_MASTER c ON e.ALF_PE = c.ALF_PE
    WHERE e.EVENT_CD IN (
        '12CN.',  -- FH: MI 1st degree female relative <65
        '12CL.',  -- FH: Angina 1st degree female relative <65
        '12CP.',  -- FH: MI 1st degree male relative <55
        '12CM.'   -- FH: Angina 1st degree male relative <55
    )
    AND e.EVENT_DT < c.FIRST_DATE
)

--SELECT * FROM fh_cvd
,

--SMOKING STATUS
SMOKING_ALL AS (
    -- Ex smoker
    SELECT e.ALF_PE, e.EVENT_DT, 'EX' AS SMOKER
    FROM SAILW1483V.EXTRACT_P2_WLGP_GP_EVENT_CLEANSED e
    INNER JOIN SAILW1483V.P2_DIABETES_COHORT_MASTER c ON e.ALF_PE = c.ALF_PE
    WHERE e.EVENT_CD IN (
        '1379.',  -- Ex-moderate smoker
        '137B.',  -- Ex-very heavy smoker
        '137F.',  -- Ex-smoker - amount unknown
        '137j.',  -- Ex-cigarette smoker
        '9km..',  -- Ex-smoker annual review
        '137A.',  -- Ex-heavy smoker
        '137S.',  -- Ex smoker
        '137l.',  -- (variant)
        '137N.',  -- Ex pipe smoker
        '1377',   -- Ex-trivial smoker
        '1378',   -- Ex-light smoker
        '1370.'   -- Stopped smoking
    )
    AND e.EVENT_DT < c.FIRST_DATE

    UNION ALL

    -- Never smoked
    SELECT e.ALF_PE, e.EVENT_DT, 'NEVER' AS SMOKER
    FROM SAILW1483V.EXTRACT_P2_WLGP_GP_EVENT_CLEANSED e
    INNER JOIN SAILW1483V.P2_DIABETES_COHORT_MASTER c ON e.ALF_PE = c.ALF_PE
    WHERE e.EVENT_CD = '1371.'
    AND e.EVENT_DT < c.FIRST_DATE

    UNION ALL

    -- Heavy smoker
    SELECT e.ALF_PE, e.EVENT_DT, 'HEAVY' AS SMOKER
    FROM SAILW1483V.EXTRACT_P2_WLGP_GP_EVENT_CLEANSED e
    INNER JOIN SAILW1483V.P2_DIABETES_COHORT_MASTER c ON e.ALF_PE = c.ALF_PE
    WHERE e.EVENT_CD IN ('1375.', '1376.')
    AND e.EVENT_DT < c.FIRST_DATE

    UNION ALL

    -- Moderate smoker
    SELECT e.ALF_PE, e.EVENT_DT, 'MODERATE' AS SMOKER
    FROM SAILW1483V.EXTRACT_P2_WLGP_GP_EVENT_CLEANSED e
    INNER JOIN SAILW1483V.P2_DIABETES_COHORT_MASTER c ON e.ALF_PE = c.ALF_PE
    WHERE e.EVENT_CD = '1374.'
    AND e.EVENT_DT < c.FIRST_DATE

    UNION ALL

    -- Light smoker
    SELECT e.ALF_PE, e.EVENT_DT, 'LIGHT' AS SMOKER
    FROM SAILW1483V.EXTRACT_P2_WLGP_GP_EVENT_CLEANSED e
    INNER JOIN SAILW1483V.P2_DIABETES_COHORT_MASTER c ON e.ALF_PE = c.ALF_PE
    WHERE e.EVENT_CD = '1373.'
    AND e.EVENT_DT < c.FIRST_DATE
),

SMOKING_RANKED AS (
    SELECT
        ALF_PE,
        SMOKER,
        ROW_NUMBER() OVER (
            PARTITION BY ALF_PE
            ORDER BY EVENT_DT DESC
        ) AS RN
    FROM SMOKING_ALL
),

SMOKING AS (
    SELECT ALF_PE, SMOKER
    FROM SMOKING_RANKED
    WHERE RN = 1
)
--SELECT * FROM smoking ORDER BY alf_pe
,

GP_CKD AS
(
SELECT
ALF_PE,
MAX(CKD) AS CKD
FROM
(
SELECT
GP.ALF_PE,
CASE WHEN EVENT_VAL < 60 THEN 1 ELSE 0 END AS CKD
FROM SAILW1483V.EXTRACT_P2_WLGP_GP_EVENT_CLEANSED GP

JOIN SAILW1483V.P2_DIABETES_COHORT_MASTER G
ON G.ALF_PE = GP.ALF_PE

JOIN SAILUKHDV.READ_CD_CV2_SCD R
ON GP.EVENT_CD = R.READ_CODE

WHERE (R.PREF_TERM_30 LIKE('%eGFR%') OR R.PREF_TERM_30 LIKE('%Glom%'))
		AND EVENT_DT < FIRST_DATE
		AND EVENT_VAL IS NOT NULL
		AND EVENT_VAL > 0	
)
GROUP BY ALF_PE
)

--SELECT * FROM GP_CKD
,


WRRS_CKD AS
(
SELECT
ALF_PE,
MAX(CKD) AS CKD
FROM
(
SELECT
ALF_PE, 
CASE WHEN CAST(VAL AS INTEGER) < 60 THEN 1 ELSE 0 END AS CKD
FROM
(
SELECT
	W.ALF_PE,
	FIRST_DATE AS DIAG,
	SPCM_COLLECTED_DT AS TEST,
	VAL_TYPE,
	CODE,	
	NAME,	
	READ_CD,
	CASE 
		WHEN VAL = '>90' THEN 91
		WHEN VAL = '>60' THEN 61
		ELSE VAL END AS VAL,	
	UNITOFMEASUREMENT
FROM 
	SAILW1483V.EXTRACT_P2_WRRS_OBSERVATION_RESULT W

JOIN SAILW1483V.P2_DIABETES_COHORT_MASTER G
ON W.ALF_PE = G.ALF_PE
	
WHERE NAME LIKE('%GFR%')
	AND SPCM_COLLECTED_DT < FIRST_DATE
	AND VAL IS NOT NULL
	AND VAL_TYPE = 'SN'
	AND VAL NOT IN('AMENDED RESULT','*','{redacted}','NA (Haemolysed specimen)','Serum Haemolysed','Not available.','NA (No sample)','NA','Insufficient sample','<0.1','NA (TEST NOT PERFORMED.)','NA (Insufficient)','>165','<20','Not Tested','<18','<15','Not Available','>3270.8','<13')
)
)
GROUP BY ALF_PE
)

--SELECT * FROM WRRS_EGFR
,

CKD AS
(
SELECT
ALF_PE,
MAX(CKD) AS CKD
FROM
(
SELECT
ALF_PE,
CKD
FROM GP_CKD

UNION

SELECT
ALF_PE,
CKD
FROM WRRS_CKD
)
GROUP BY ALF_PE
)
,

MORBS AS
(
SELECT
A.ALF_PE,
GP.EVENT_DT,
M.READ_TYPE
FROM ALFS A

JOIN SAILW1483V.EXTRACT_P2_WLGP_GP_EVENT_CLEANSED GP
ON A.ALF_PE = GP.ALF_PE

JOIN SAILW1483V.PHEN_MORB_READ M
ON GP.EVENT_CD = M.READ_CODE

WHERE GP.EVENT_DT < FIRST_DATE
)
,

MORB_SELECT AS
(
SELECT
ALF_PE,
EVENT_DT,
READ_TYPE
FROM 
(
SELECT
*,
ROW_NUMBER() OVER(PARTITION BY ALF_PE, READ_TYPE ORDER BY EVENT_DT) AS RANK
FROM MORBS

WHERE READ_TYPE IN('DIABETES','DEMENTIA','LIVER_DISEASE','HEART_FAILURE','HYPERTENSION','AF')
)
WHERE RANK = 1
)
,

MORB_MAX AS
(
SELECT
ALF_PE,
MAX (DIABETES) 				AS DM,
MAX (DEMENTIA) 				AS DMTA,
MAX (LIVER) 				AS LVR,
MAX (HF) 					AS HF,
MAX (HYPERTENSION) 			AS HTN,
MAX (AF) 					AS AF,
MAX (RA) 					AS RA,
MAX (FH_CVD) 				AS FH_CVD,
MAX (CKD) 					AS CKD,
MAX (SMOKING_STATUS) 		AS SMK
FROM 
(
SELECT 
A.ALF_PE,
CASE WHEN READ_TYPE = 'DIABETES' 			THEN 1 ELSE 0 END AS DIABETES,
CASE WHEN READ_TYPE = 'DEMENTIA'			THEN 1 ELSE 0 END AS DEMENTIA,
CASE WHEN READ_TYPE = 'LIVER_DISEASE' 		THEN 1 ELSE 0 END AS LIVER,
CASE WHEN READ_TYPE = 'HEART_FAILURE' 		THEN 1 ELSE 0 END AS HF,
CASE WHEN READ_TYPE = 'HYPERTENSION' 		THEN 1 ELSE 0 END AS HYPERTENSION,
CASE WHEN READ_TYPE = 'AF' 					THEN 1 ELSE 0 END AS AF,
CASE WHEN ra.ALF_PE IS NOT NULL 			THEN 1 ELSE 0 END AS RA,
CASE WHEN fh.ALF_PE IS NOT NULL 			THEN 1 ELSE 0 END AS FH_CVD,
CASE WHEN ckd.ALF_PE IS NOT NULL 			THEN 1 ELSE 0 END AS CKD,
smk.SMOKER AS SMOKING_STATUS
FROM MORB_SELECT A

LEFT JOIN RA       ra  ON ra.ALF_PE  = A.ALF_PE
LEFT JOIN FH_CVD   fh  ON fh.ALF_PE  = A.ALF_PE
LEFT JOIN SMOKING  smk ON smk.ALF_PE = A.ALF_PE
LEFT JOIN CKD  	   ckd ON ckd.ALF_PE = A.ALF_PE
)
GROUP BY ALF_PE
)
,

NHDL_READ AS
(
SELECT
ALF_PE,
EVENT_DT_LIPID AS TEST,
EVENT_VAL
FROM
(
SELECT 
	T.ALF_PE,
	T.EVENT_DT AS EVENT_DT_LIPID,
	T.EVENT_VAL - H.EVENT_VAL AS EVENT_VAL
FROM
(
SELECT 
	M.ALF_PE,
	GP.EVENT_DT,
	GP.EVENT_VAL
FROM ALFS M

JOIN SAILW1483V.EXTRACT_P2_WLGP_GP_EVENT_CLEANSED GP
ON M.ALF_PE = GP.ALF_PE

JOIN SAILW1483V.PHEN_LIPID_READ D
ON GP.EVENT_CD = D.READ_CODE

WHERE GP.EVENT_DT BETWEEN FIRST_DATE - 1 YEAR AND FIRST_DATE + 30 DAYS
AND READ_TYPE = 'TC'
) T

JOIN
(
SELECT 
	M.ALF_PE,
	GP.EVENT_DT,
	GP.EVENT_VAL
FROM ALFS M

JOIN SAILW1483V.EXTRACT_P2_WLGP_GP_EVENT_CLEANSED GP
ON M.ALF_PE = GP.ALF_PE

JOIN SAILW1483V.PHEN_LIPID_READ D
ON GP.EVENT_CD = D.READ_CODE

WHERE GP.EVENT_DT BETWEEN FIRST_DATE - 1 YEAR AND FIRST_DATE + 30 DAYS
AND READ_TYPE = 'HDL'
) H
ON T.ALF_PE = H.ALF_PE
AND T.EVENT_DT = H.EVENT_DT

UNION

SELECT 
	M.ALF_PE,
	GP.EVENT_DT AS EVENT_DT_LIPID,
	GP.EVENT_VAL
FROM ALFS M

JOIN SAILW1483V.EXTRACT_P2_WLGP_GP_EVENT_CLEANSED GP
ON M.ALF_PE = GP.ALF_PE

JOIN SAILW1483V.PHEN_LIPID_READ D
ON GP.EVENT_CD = D.READ_CODE

WHERE GP.EVENT_DT BETWEEN FIRST_DATE - 1 YEAR AND FIRST_DATE + 30 DAYS
AND READ_TYPE = 'NON_HDL'
)
),

NHDL_WRRS AS
(
SELECT
ALF_PE,
TEST,
VAL AS EVENT_VAL
FROM
(
SELECT
	W.ALF_PE,
	SPCM_COLLECTED_DT AS TEST,
	VAL_TYPE,
	CODE,	
	NAME,	
	READ_CD,
	CAST(VAL AS DECIMAL(31,8)) AS VAL,	
	UNITOFMEASUREMENT
FROM 
	SAILW1483V.EXTRACT_P2_WRRS_OBSERVATION_RESULT W

JOIN ALFS F
ON W.ALF_PE = F.ALF_PE
	
WHERE CODE LIKE('NHDL%')
	AND SPCM_COLLECTED_DT BETWEEN FIRST_DATE - 1 YEAR AND FIRST_DATE + 30 DAYS
	AND VAL IS NOT NULL
	AND VAL > 0
	AND VAL_TYPE = 'SN'
	AND VAL NOT IN('{redacted}','Serum Haemolysed','Not available.','NA (No sample)','NA','Insufficient sample','<0.1','NA (TEST NOT PERFORMED.)','NA (Insufficient)')
)
)
,

NHDL AS
(
SELECT
ALF_PE,
NHDL,
NHDL_VAL
FROM
(
SELECT
ALF_PE,
CASE 
	WHEN EVENT_VAL > 4.3 THEN '> 4.3'		
	WHEN EVENT_VAL <= 4.3 THEN '<= 4.3'		
END AS NHDL,
EVENT_VAL AS NHDL_VAL,
ROW_NUMBER() OVER(PARTITION BY ALF_PE ORDER BY TEST DESC) AS RANK
FROM
(
SELECT
*
FROM NHDL_WRRS

UNION

SELECT
*
FROM NHDL_READ
)
)
WHERE RANK = 1
)
,

TC_HDL AS
(
SELECT
ALF_PE,
TC_HDL
FROM
(
	SELECT
	ALF_PE,
	EVENT_VAL AS TC_HDL,
	ROW_NUMBER() OVER(PARTITION BY ALF_PE ORDER BY EVENT_DT DESC) AS RANK
	FROM
	(
		SELECT 
			T.ALF_PE,
			T.EVENT_DT,
			CAST(T.EVENT_VAL AS DECIMAL(31,8)) / CAST(H.EVENT_VAL AS DECIMAL(31,8)) AS EVENT_VAL
		FROM
		(
			SELECT 
				M.ALF_PE,
				GP.EVENT_DT,
				GP.EVENT_VAL
			FROM ALFS M
			
			JOIN SAILW1483V.EXTRACT_P2_WLGP_GP_EVENT_CLEANSED GP
			ON M.ALF_PE = GP.ALF_PE
			
			JOIN SAILW1483V.PHEN_LIPID_READ D
			ON GP.EVENT_CD = D.READ_CODE
			
			WHERE GP.EVENT_DT BETWEEN FIRST_DATE - 1 YEAR AND FIRST_DATE + 30 DAYS
			AND READ_TYPE = 'TC'
		) T
		
		JOIN
		(
			SELECT 
				M.ALF_PE,
				GP.EVENT_DT,
				GP.EVENT_VAL
			FROM ALFS M
			
			JOIN SAILW1483V.EXTRACT_P2_WLGP_GP_EVENT_CLEANSED GP
			ON M.ALF_PE = GP.ALF_PE
			
			JOIN SAILW1483V.PHEN_LIPID_READ D
			ON GP.EVENT_CD = D.READ_CODE
			
			WHERE GP.EVENT_DT BETWEEN FIRST_DATE - 1 YEAR AND FIRST_DATE + 30 DAYS
			AND READ_TYPE = 'HDL'
		) H
		ON T.ALF_PE = H.ALF_PE
		AND T.EVENT_DT = H.EVENT_DT
	)
)
WHERE RANK = 1
)
,

EGFR_READ AS
(
SELECT
ALF_PE,
EVENT_DT_EGFR AS TEST,
EVENT_VAL
FROM
(
SELECT
	M.ALF_PE,
	EVENT_CD,
	EVENT_DT AS EVENT_DT_EGFR,
	EVENT_VAL,
	CASE
		WHEN R.PREF_TERM_198 IS NULL AND R.PREF_TERM_60 IS NULL THEN R.PREF_TERM_30
		WHEN R.PREF_TERM_198 IS NULL THEN R.PREF_TERM_60
		ELSE PREF_TERM_198
	END AS DESC		
FROM ALFS M

JOIN SAILW1483V.EXTRACT_P2_WLGP_GP_EVENT_CLEANSED GP
ON M.ALF_PE = GP.ALF_PE

LEFT JOIN SAILUKHDV.READ_CD_CV2_SCD R
ON GP.EVENT_CD = R.READ_CODE
	
WHERE 
	GP.EVENT_DT BETWEEN FIRST_DATE - 1 YEAR AND FIRST_DATE + 30 DAYS
	AND (R.PREF_TERM_30 LIKE('%eGFR%')
		OR R.PREF_TERM_30 LIKE('%Glom%'))
	AND EVENT_VAL IS NOT NULL
	AND EVENT_VAL > 0
)
),

EGFR_WRRS AS
(
SELECT
ALF_PE,
TEST,
VAL AS EVENT_VAL
FROM
(
SELECT
	W.ALF_PE,
	SPCM_COLLECTED_DT AS TEST,
	VAL_TYPE,
	CODE,	
	NAME,	
	READ_CD,
	CAST(
	CASE 
		WHEN VAL = '>90' THEN 91
		WHEN VAL = '>60' THEN 61
		ELSE VAL END
	AS INTEGER) AS VAL,	
	UNITOFMEASUREMENT
FROM 
	SAILW1483V.EXTRACT_P2_WRRS_OBSERVATION_RESULT W

JOIN ALFS F
ON W.ALF_PE = F.ALF_PE
	
WHERE NAME LIKE('%GFR%')
	AND SPCM_COLLECTED_DT BETWEEN FIRST_DATE - 1 YEAR AND FIRST_DATE + 30 DAYS
	AND VAL IS NOT NULL
	AND VAL_TYPE = 'SN'
	AND VAL NOT IN('{redacted}','Serum Haemolysed','Not available.','NA (No sample)','NA','Insufficient sample','<0.1','NA (TEST NOT PERFORMED.)','NA (Insufficient)','>165','<20','Not Tested','<18','<15','Not Available','>3270.8','<13','NA (Haemolysed specimen)')
)
),

EGFR AS
(
SELECT
ALF_PE,
EGFR,
EGFR_VAL
FROM
(
SELECT
ALF_PE,
CASE 
	WHEN EVENT_VAL > 60 THEN '> 60'
	WHEN EVENT_VAL BETWEEN 30 AND 60 THEN '30 - 60'		
	WHEN EVENT_VAL < 30 THEN '< 30'		
END AS EGFR,
EVENT_VAL AS EGFR_VAL,
ROW_NUMBER() OVER(PARTITION BY ALF_PE ORDER BY TEST DESC) AS RANK
FROM
(
SELECT
*
FROM EGFR_WRRS

UNION

SELECT
*
FROM EGFR_READ
)
)
WHERE RANK = 1
)
,

LDL_READ AS
(
SELECT
ALF_PE,
FIRST_DATE,
EVENT_DT_LIPID AS TEST,
EVENT_VAL
FROM
(
SELECT 
	M.ALF_PE,
	FIRST_DATE,
	GP.EVENT_DT AS EVENT_DT_LIPID,
	GP.EVENT_VAL,
	D.READ_TYPE,
	D.READ_CODE	
FROM ALFS M

JOIN SAILW1483V.EXTRACT_P2_WLGP_GP_EVENT_CLEANSED GP
ON M.ALF_PE = GP.ALF_PE

JOIN SAILW1483V.PHEN_LIPID_READ D
ON GP.EVENT_CD = D.READ_CODE

WHERE GP.EVENT_DT BETWEEN FIRST_DATE - 1 YEAR AND FIRST_DATE + 30 DAYS
AND READ_TYPE = 'LDL'

ORDER BY M.ALF_PE, GP.EVENT_DT
)
),

LDL_WRRS AS
(
SELECT
ALF_PE,
FIRST_DATE,
TEST,
VAL AS EVENT_VAL
FROM
(
SELECT
	W.ALF_PE,
	FIRST_DATE,
	SPCM_COLLECTED_DT AS TEST,
	VAL_TYPE,
	CODE,	
	NAME,	
	READ_CD,
	CAST(VAL AS DECIMAL(31,8)) AS VAL,	
	UNITOFMEASUREMENT
FROM 
	SAILW1483V.EXTRACT_P2_WRRS_OBSERVATION_RESULT W

JOIN ALFS F
ON W.ALF_PE = F.ALF_PE
	
WHERE CODE LIKE('LDL%')
	AND SPCM_COLLECTED_DT BETWEEN FIRST_DATE - 1 YEAR AND FIRST_DATE + 30 DAYS
	AND VAL IS NOT NULL
	AND VAL_TYPE = 'SN'
	AND VAL NOT IN('{redacted}','Serum Haemolysed','Not available.','NA (No sample)','NA','Insufficient sample','<0.1','NA (TEST NOT PERFORMED.)','NA (Insufficient)')
)
)
,

LDL AS
(
SELECT
ALF_PE, 
TEST,
LDL, 
LDL_VAL
FROM
(
SELECT
ALF_PE,
FIRST_DATE,
CASE 
	WHEN EVENT_VAL > 3.5 THEN '> 3.5'		
	WHEN EVENT_VAL BETWEEN 2.5 AND 3.5 THEN '2.5 - 3.5'	
	WHEN EVENT_VAL < 2.5 THEN '< 2.5'		
END AS LDL,
EVENT_VAL AS LDL_VAL,
TEST,
ROW_NUMBER() OVER(PARTITION BY ALF_PE ORDER BY TEST DESC) AS RANK
FROM
(
SELECT
*
FROM LDL_WRRS

UNION

SELECT
*
FROM LDL_READ
)
)
WHERE RANK = 1
)
,

ALF_LDL_COMB AS
(
SELECT
ALF_PE,
CASE WHEN L.ALF_PE IS NOT NULL THEN TEST ELSE A.FIRST_DATE END AS DT
FROM ALFS A

LEFT JOIN LDL L
USING (ALF_PE)
)
--SELECT COUNT(DISTINCT ALF_PE) FROM ALF_LDL_COMB
,

SBP AS
(
SELECT
ALF_PE,
SBP
FROM
(
SELECT
B.ALF_PE,
EVENT_DT,
CASE WHEN SYS = 999 OR SYS = -999 THEN NULL ELSE SYS END AS SBP,
ROW_NUMBER() OVER(PARTITION BY B.ALF_PE ORDER BY EVENT_DT DESC) AS RANK
FROM ALFS A

JOIN SAILW1483V.DM_BLOOD_PRESSURES B
ON A.ALF_PE = B.ALF_PE

WHERE B.EVENT_DT BETWEEN A.FIRST_DATE - 1 YEARS AND A.FIRST_DATE + 30 DAYS
)
WHERE RANK = 1
)
,

LLT AS
(
SELECT
ALF_PE,
CASE 
	WHEN INEGY = 1 THEN 4
	WHEN (HI_STAT = 1 OR LI_STAT = 1) AND EZET_FIBR = 1 THEN 4
	WHEN HI_STAT = 1 AND LI_STAT = 1 THEN 3
	WHEN HI_STAT = 1 THEN 3		
	WHEN LI_STAT = 1 THEN 2	
	WHEN EZET_FIBR = 1 THEN 1
	ELSE 0
END AS LLT_INT,
CASE 
	WHEN INEGY = 1 OR HI_STAT = 1 OR LI_STAT = 1 THEN 1
	ELSE 0
END AS STATIN
FROM
(
SELECT
ALF_PE,
MAX(HI_STAT) AS HI_STAT,
MAX(LI_STAT) AS LI_STAT,
MAX(INEGY) AS INEGY,
MAX(EZET_FIBR) AS EZET_FIBR
FROM 
(
SELECT
A.ALF_PE,
CASE WHEN READ_TYPE = 'HIGH_STATIN' 						THEN '1' ELSE '0' END AS HI_STAT,
CASE WHEN READ_TYPE = 'LOW_STATIN' 							THEN '1' ELSE '0' END AS LI_STAT,
CASE WHEN READ_TYPE = 'INEGY' 								THEN '1' ELSE '0' END AS INEGY,
CASE WHEN READ_TYPE = 'EZETIMIBE' OR READ_TYPE = 'FIBRATE'	THEN '1' ELSE '0' END AS EZET_FIBR
FROM ALF_LDL_COMB A

JOIN SAILW1483V.EXTRACT_P2_WLGP_GP_EVENT_CLEANSED GP
ON A.ALF_PE = GP.ALF_PE

JOIN SAILW1483V.PHEN_DRUG_READ D
ON GP.EVENT_CD = D.READ_CODE

WHERE EVENT_DT BETWEEN DT - 60 DAYS AND DT
AND READ_TYPE IN('HIGH_STATIN', 'LOW_STATIN', 'INEGY', 'EZETIMIBE', 'FIBRATE')
)
GROUP BY ALF_PE
)
)
,

ANTI_HTN_1 AS 
(
SELECT
GP.ALF_PE,
CASE WHEN L.ANTIHYPERTENSIVE_CLASS LIKE 'CENTRAL' THEN 'X'
WHEN L.ANTIHYPERTENSIVE_CLASS LIKE 'ALFA' THEN 'L'
ELSE L.ANTIHYPERTENSIVE_CLASS END AS DRUG_CLASS
FROM ALFS A

JOIN SAILW1483V.EXTRACT_P2_WLGP_GP_EVENT_CLEANSED GP
ON A.ALF_PE = GP.ALF_PE

JOIN SAILW1483V.HYPERTENSIVE_DRUGS L
ON GP.EVENT_CD = L.READ_CODE

WHERE EVENT_DT BETWEEN FIRST_DATE - 60 DAYS AND FIRST_DATE
)
,

ANTI_HTN_2 AS 
(
SELECT 
ALF_PE,
MAX(CASE WHEN DRUG_CLASS LIKE '%A%' THEN 1 ELSE 0 END) AS DRUG_A,
MAX(CASE WHEN DRUG_CLASS LIKE '%B%' THEN 1 ELSE 0 END) AS DRUG_B,
MAX(CASE WHEN DRUG_CLASS LIKE '%C%' THEN 1 ELSE 0 END) AS DRUG_C,
MAX(CASE WHEN DRUG_CLASS LIKE '%D%' THEN 1 ELSE 0 END) AS DRUG_D,
MAX(CASE WHEN DRUG_CLASS LIKE '%K%' THEN 1 ELSE 0 END) AS DRUG_K,
MAX(CASE WHEN DRUG_CLASS LIKE '%L%' THEN 1 ELSE 0 END) AS DRUG_ALFA,
MAX(CASE WHEN DRUG_CLASS LIKE '%V%' THEN 1 ELSE 0 END) AS DRUG_V,
MAX(CASE WHEN DRUG_CLASS LIKE '%X%' THEN 1 ELSE 0 END) AS DRUG_Central
FROM ANTI_HTN_1

GROUP BY ALF_PE
)
,

ANTI_HTN AS
(
SELECT
ALF_PE,
CASE WHEN CLASSES >= 4 THEN 4 ELSE CLASSES END AS AHT_INT,
CASE WHEN CLASSES >= 1 THEN 1 ELSE 0 END AS AHT
FROM
(
SELECT 
A.ALF_PE,
CASE WHEN P.ALF_PE IS NOT NULL THEN (DRUG_A + DRUG_B + DRUG_C + DRUG_D + DRUG_K + DRUG_ALFA + DRUG_V + DRUG_Central) 
ELSE 0 END AS CLASSES 
FROM ALFS A

LEFT JOIN ANTI_HTN_2 P
USING(ALF_PE)
)
)

SELECT 
	M.ALF_PE, 
	M.FIRST_DATE AS DIAG_DT,
	M.CENSOR_DATE AS CNS_DT,
	'DM' AS COHORT,
	G.LSOA2011_CD AS LSOA,
	G.MSOA_CD AS MSOA,
	G.LAD_CD AS LAD,
	NULL AS HE,
	CASE 
	WHEN M.GENDER = 1 THEN 'M'
	WHEN M.GENDER = 2 THEN 'F'
	ELSE NULL END AS SEX, 
	G.WIMD_2019_QUINTILE AS WIMD, 
	td.tds AS TOWNSEND,
    COALESCE(M.ETHNICITY, 'Unknown')    AS ETHN,
	M.AGE_DIAG AS AGE, 
	M.TYPE, 
	SMK,
	M.BMI,
	CASE WHEN DM IS NULL THEN 0 ELSE DM END AS DM, 
	CASE WHEN DMTA IS NULL THEN 0 ELSE DMTA END AS DMTA, 
	CASE WHEN LVR IS NULL THEN 0 ELSE LVR END AS LVR, 
	CASE WHEN HTN IS NULL THEN 0 ELSE HTN END AS HTN, 
	CASE WHEN HF IS NULL THEN 0 ELSE HF END AS HF,
	CASE WHEN AF IS NULL THEN 0 ELSE AF END AS AF,	
	CASE WHEN RA IS NULL THEN 0 ELSE RA END AS RA,
	CASE WHEN FH_CVD IS NULL THEN 0 ELSE FH_CVD END AS FH_CVD,	
	CASE WHEN CKD IS NULL THEN 0 ELSE CKD END AS CKD,		
	CASE WHEN LLT_INT IS NULL THEN 0 ELSE LLT_INT END AS LLT_INT,
	CASE WHEN STATIN IS NULL THEN 0 ELSE STATIN END AS STATIN,	
	CASE WHEN AHT_INT IS NULL THEN 0 ELSE AHT_INT END AS AHT_INT,	
	CASE WHEN AHT IS NULL THEN 0 ELSE AHT END AS AHT,
	LDL,
	LDL_VAL,	
	NHDL,
	NHDL_VAL,
	TC_HDL,
	EGFR,
	EGFR_VAL,
	SBP AS SBP_VAL
FROM SAILW1483V.P2_DIABETES_COHORT_MASTER M

JOIN ALFS A
USING(ALF_PE)

LEFT JOIN MORB_MAX X
USING(ALF_PE)

LEFT JOIN 
(
SELECT
L.*,
MSOA11CD AS MSOA_CD,
LAD11CD AS LAD_CD
FROM
(
SELECT 
W.*,
ROW_NUMBER() OVER(PARTITION BY W.ALF_PE ORDER BY START_DATE DESC) AS RANK
FROM SAILW1483V.EXTRACT_P2_WDSD_SINGLE_CLEAN_GEO_CHAR_LSOA2011  W

JOIN SAILW1483V.P2_DIABETES_COHORT_MASTER M
USING(ALF_PE)

WHERE 
LSOA2011_CD <> 'N/A' 
AND ((M.FIRST_DATE BETWEEN START_DATE AND END_DATE) 
	OR (M.FIRST_DATE < START_DATE AND END_DATE = '9999-01-01'))
) L

JOIN (SELECT LSOA11CD, MSOA11CD, LAD11CD FROM SAILW1483V.LSOA_MSOA_LAD_ENGLAND_WALES WHERE LSOA11CD LIKE ('W%') GROUP BY LSOA11CD, MSOA11CD, LAD11CD) W
ON LSOA2011_CD = LSOA11CD

WHERE RANK = 1
) G
USING(ALF_PE)

LEFT JOIN EGFR E
USING (ALF_PE)

LEFT JOIN NHDL N
USING (ALF_PE)

LEFT JOIN LDL L
USING (ALF_PE)

LEFT JOIN SBP S
USING (ALF_PE)

LEFT JOIN TC_HDL
USING (ALF_PE)

LEFT JOIN LLT
USING (ALF_PE)

LEFT JOIN ANTI_HTN
USING (ALF_PE)

LEFT JOIN SAILW1483V.TOWNS_DEP_SCORE td 
ON td.GEO_CODE = G.LSOA2011_CD

WHERE M.AGE_DIAG BETWEEN 25 AND 84
AND M.INC_WITH_ASCVD = 0
; 
COMMIT;
--
------------------------------------------
--
-- Select all results
SELECT 
*
FROM 
	SAILW1483V.CAPSTONE_DM_RISK_CALCULATION;
--
-- Count all results
SELECT 
	COUNT(*)
FROM 
	SAILW1483V.CAPSTONE_DM_RISK_CALCULATION;
	
SELECT 
	COUNT(DISTINCT ALF_PE)
FROM 
	SAILW1483V.CAPSTONE_DM_RISK_CALCULATION;

------------------------------------------
--
--Drop Table
CALL FNC.DROP_IF_EXISTS('SAILW1483V.CAPSTONE_ASCVD_RISK_CALCULATION');
COMMIT;
------------------------------------------ 
--
-- Create Table
CREATE TABLE SAILW1483V.CAPSTONE_ASCVD_RISK_CALCULATION
(
	ALF_PE			BIGINT,
	DIAG_DT			DATE,
	CNS_DT			DATE,
	COHORT			VARCHAR(10),
	LSOA			VARCHAR(10),
	MSOA			VARCHAR(10),
	LAD				VARCHAR(10),
	HE				INTEGER,
	SEX				VARCHAR(1),
	WIMD			INTEGER,
	TOWNSEND		DECIMAL(31,8),
	ETHN			VARCHAR(10),
	AGE				INTEGER,
	TYPE			VARCHAR(10),
	SMK				VARCHAR(10),
	BMI				DECIMAL(31,8),
	DM				INTEGER,
	DMTA			INTEGER,
	LVR				INTEGER,
	HTN				INTEGER,
	HF				INTEGER,
	AF				INTEGER,
	RA				INTEGER,
	FH_CVD			INTEGER,
	CKD				INTEGER,
	LLT_INT			INTEGER,
	STATIN			INTEGER,	
	AHT_INT			INTEGER,
	AHT				INTEGER,	
	LDL				VARCHAR(10),
	LDL_VAL			DECIMAL(31,8),
	NHDL			VARCHAR(10),	
	NHDL_VAL		DECIMAL(31,8),
	TC_HDL			DECIMAL(31,8),	
	EGFR			VARCHAR(10),	
	EGFR_VAL		DECIMAL(31,8),
	SBP_VAL			DECIMAL(31,8)
) 
;
COMMIT;
------------------------------------------
--
--Insert into Table
INSERT INTO SAILW1483V.CAPSTONE_ASCVD_RISK_CALCULATION
--
WITH ALFS AS
(
SELECT 
	ALF_PE,
	FIRST_DATE
FROM 
	SAILW1483V.COHORT_MASTER_FINAL M

WHERE YEAR(FIRST_DATE) IN(2022,2023)
)

--SELECT COUNT(DISTINCT ALF_PE) FROM ALFS
,

-- RHEUMATOID ARTHRITIS  
RA_WLGP AS (
    SELECT DISTINCT e.ALF_PE
    FROM SAILW1483V.EXTRACT_WLGP_GP_EVENT_CLEANSED e
    INNER JOIN SAILW1483V.COHORT_MASTER_FINAL c ON e.ALF_PE = c.ALF_PE
    WHERE e.EVENT_CD IN (
        '66HB0',  -- RA monitoring
        'N040.',  -- Rheumatoid arthritis
        'N0402',  -- RA of shoulder
        'N0408',  -- RA of MCP joint
        'N0409',  -- RA of PIP joint of finger
        'N0405',  -- RA of elbow
        'N0400',  -- RA of cervical spine
        'N040D',  -- RA of knee
        'N040F',  -- RA of ankle
        'N04..',  -- RA and other inflammatory polyarthropathy
        'N0407',  -- RA of wrist
        'N040C',  -- RA of sacro-iliac joint
        'N0406',  -- RA of distal radio-ulnar joint
        'N040A',  -- RA of DIP joint of finger
        'N040B'   -- RA of hip
    )
    AND e.EVENT_DT < c.FIRST_DATE
),

RA_PEDW AS (
    SELECT DISTINCT S.ALF_PE
    FROM SAILW1483V.EXTRACT_PEDW_SPELL S
    
JOIN SAILW1483V.EXTRACT_PEDW_EPISODE E
	ON E.PROV_UNIT_CD = S.PROV_UNIT_CD 
	AND E.SPELL_NUM_PE = S.SPELL_NUM_PE

JOIN SAILW1483V.EXTRACT_PEDW_DIAG D
	ON E.PROV_UNIT_CD = D.PROV_UNIT_CD
	AND E.SPELL_NUM_PE = D.SPELL_NUM_PE
	AND E.EPI_NUM = D.EPI_NUM	
 
INNER JOIN SAILW1483V.COHORT_MASTER_FINAL c ON S.ALF_PE = c.ALF_PE
    
WHERE D.DIAG_CD_1234 IN ('M069', 'M068', 'M061', 'M060', 'M064')
AND s.ADMIS_DT < c.FIRST_DATE
),

RA AS (
    SELECT ALF_PE FROM RA_WLGP
    UNION
    SELECT ALF_PE FROM RA_PEDW
)

--SELECT * FROM RA
,

--FAMILY HISTORY OF ANGINA / MI
FH_CVD AS (
    SELECT DISTINCT e.ALF_PE
    FROM SAILW1483V.EXTRACT_WLGP_GP_EVENT_CLEANSED e
    INNER JOIN SAILW1483V.COHORT_MASTER_FINAL c ON e.ALF_PE = c.ALF_PE
    WHERE e.EVENT_CD IN (
        '12CN.',  -- FH: MI 1st degree female relative <65
        '12CL.',  -- FH: Angina 1st degree female relative <65
        '12CP.',  -- FH: MI 1st degree male relative <55
        '12CM.'   -- FH: Angina 1st degree male relative <55
    )
    AND e.EVENT_DT < c.FIRST_DATE
)

--SELECT * FROM fh_cvd
,

--SMOKING STATUS
SMOKING_ALL AS (
    -- Ex smoker
    SELECT e.ALF_PE, e.EVENT_DT, 'EX' AS SMOKER
    FROM SAILW1483V.EXTRACT_WLGP_GP_EVENT_CLEANSED e
    INNER JOIN SAILW1483V.COHORT_MASTER_FINAL c ON e.ALF_PE = c.ALF_PE
    WHERE e.EVENT_CD IN (
        '1379.',  -- Ex-moderate smoker
        '137B.',  -- Ex-very heavy smoker
        '137F.',  -- Ex-smoker - amount unknown
        '137j.',  -- Ex-cigarette smoker
        '9km..',  -- Ex-smoker annual review
        '137A.',  -- Ex-heavy smoker
        '137S.',  -- Ex smoker
        '137l.',  -- (variant)
        '137N.',  -- Ex pipe smoker
        '1377',   -- Ex-trivial smoker
        '1378',   -- Ex-light smoker
        '1370.'   -- Stopped smoking
    )
    AND e.EVENT_DT < c.FIRST_DATE

    UNION ALL

    -- Never smoked
    SELECT e.ALF_PE, e.EVENT_DT, 'NEVER' AS SMOKER
    FROM SAILW1483V.EXTRACT_WLGP_GP_EVENT_CLEANSED e
    INNER JOIN SAILW1483V.COHORT_MASTER_FINAL c ON e.ALF_PE = c.ALF_PE
    WHERE e.EVENT_CD = '1371.'
    AND e.EVENT_DT < c.FIRST_DATE

    UNION ALL

    -- Heavy smoker
    SELECT e.ALF_PE, e.EVENT_DT, 'HEAVY' AS SMOKER
    FROM SAILW1483V.EXTRACT_WLGP_GP_EVENT_CLEANSED e
    INNER JOIN SAILW1483V.COHORT_MASTER_FINAL c ON e.ALF_PE = c.ALF_PE
    WHERE e.EVENT_CD IN ('1375.', '1376.')
    AND e.EVENT_DT < c.FIRST_DATE

    UNION ALL

    -- Moderate smoker
    SELECT e.ALF_PE, e.EVENT_DT, 'MODERATE' AS SMOKER
    FROM SAILW1483V.EXTRACT_WLGP_GP_EVENT_CLEANSED e
    INNER JOIN SAILW1483V.COHORT_MASTER_FINAL c ON e.ALF_PE = c.ALF_PE
    WHERE e.EVENT_CD = '1374.'
    AND e.EVENT_DT < c.FIRST_DATE

    UNION ALL

    -- Light smoker
    SELECT e.ALF_PE, e.EVENT_DT, 'LIGHT' AS SMOKER
    FROM SAILW1483V.EXTRACT_WLGP_GP_EVENT_CLEANSED e
    INNER JOIN SAILW1483V.COHORT_MASTER_FINAL c ON e.ALF_PE = c.ALF_PE
    WHERE e.EVENT_CD = '1373.'
    AND e.EVENT_DT < c.FIRST_DATE
),

SMOKING_RANKED AS (
    SELECT
        ALF_PE,
        SMOKER,
        ROW_NUMBER() OVER (
            PARTITION BY ALF_PE
            ORDER BY EVENT_DT DESC
        ) AS RN
    FROM SMOKING_ALL
),

SMOKING AS (
    SELECT ALF_PE, SMOKER
    FROM SMOKING_RANKED
    WHERE RN = 1
)
--SELECT * FROM smoking ORDER BY alf_pe
,

GP_CKD AS
(
SELECT
ALF_PE,
MAX(CKD) AS CKD
FROM
(
SELECT
GP.ALF_PE,
CASE WHEN EVENT_VAL < 60 THEN 1 ELSE 0 END AS CKD
FROM SAILW1483V.EXTRACT_WLGP_GP_EVENT_CLEANSED GP

JOIN SAILW1483V.COHORT_MASTER_FINAL G
ON G.ALF_PE = GP.ALF_PE

JOIN SAILUKHDV.READ_CD_CV2_SCD R
ON GP.EVENT_CD = R.READ_CODE

WHERE (R.PREF_TERM_30 LIKE('%eGFR%') OR R.PREF_TERM_30 LIKE('%Glom%'))
		AND EVENT_DT < FIRST_DATE
		AND EVENT_VAL IS NOT NULL
		AND EVENT_VAL > 0	
)
GROUP BY ALF_PE
)

--SELECT * FROM GP_CKD
,


WRRS_CKD AS
(
SELECT
ALF_PE,
MAX(CKD) AS CKD
FROM
(
SELECT
ALF_PE, 
CASE WHEN CAST(VAL AS INTEGER) < 60 THEN 1 ELSE 0 END AS CKD
FROM
(
SELECT
	W.ALF_PE,
	FIRST_DATE AS DIAG,
	SPCM_COLLECTED_DT AS TEST,
	VAL_TYPE,
	CODE,	
	NAME,	
	READ_CD,
	CASE 
		WHEN VAL = '>90' THEN 91
		WHEN VAL = '>60' THEN 61
		ELSE VAL END AS VAL,	
	UNITOFMEASUREMENT
FROM 
	SAILW1483V.EXTRACT_WRRS_OBSERVATION_RESULT W

JOIN SAILW1483V.COHORT_MASTER_FINAL G
ON W.ALF_PE = G.ALF_PE
	
WHERE NAME LIKE('%GFR%')
	AND SPCM_COLLECTED_DT < FIRST_DATE
	AND VAL IS NOT NULL
	AND VAL_TYPE = 'SN'
	AND VAL NOT IN('AMENDED RESULT','*','{redacted}','NA (Haemolysed specimen)','Serum Haemolysed','Not available.','NA (No sample)','NA','Insufficient sample','<0.1','NA (TEST NOT PERFORMED.)','NA (Insufficient)','>165','<20','Not Tested','<18','<15','Not Available','>3270.8','<13')
)
)
GROUP BY ALF_PE
)

--SELECT * FROM WRRS_EGFR
,

CKD AS
(
SELECT
ALF_PE,
MAX(CKD) AS CKD
FROM
(
SELECT
ALF_PE,
CKD
FROM GP_CKD

UNION

SELECT
ALF_PE,
CKD
FROM WRRS_CKD
)
GROUP BY ALF_PE
)
,

MORBS AS
(
SELECT
A.ALF_PE,
GP.EVENT_DT,
M.READ_TYPE
FROM ALFS A

JOIN SAILW1483V.EXTRACT_WLGP_GP_EVENT_CLEANSED GP
ON A.ALF_PE = GP.ALF_PE

JOIN SAILW1483V.PHEN_MORB_READ M
ON GP.EVENT_CD = M.READ_CODE

WHERE GP.EVENT_DT < FIRST_DATE
)
,

MORB_SELECT AS
(
SELECT
ALF_PE,
EVENT_DT,
READ_TYPE
FROM 
(
SELECT
*,
ROW_NUMBER() OVER(PARTITION BY ALF_PE, READ_TYPE ORDER BY EVENT_DT) AS RANK
FROM MORBS

WHERE READ_TYPE IN('DIABETES','DEMENTIA','LIVER_DISEASE','HEART_FAILURE','AF','HYPERTENSION')
)
WHERE RANK = 1
)
,

MORB_MAX AS
(
SELECT
ALF_PE,
MAX (DIABETES) 				AS DM,
MAX (DEMENTIA) 				AS DMTA,
MAX (LIVER) 				AS LVR,
MAX (HF) 					AS HF,
MAX (HYPERTENSION) 			AS HTN,
MAX (AF) 					AS AF,
MAX (RA) 					AS RA,
MAX (FH_CVD) 				AS FH_CVD,
MAX (CKD) 					AS CKD,
MAX (SMOKING_STATUS) 		AS SMK
FROM 
(
SELECT 
A.ALF_PE,
CASE WHEN READ_TYPE = 'DIABETES' 			THEN 1 ELSE 0 END AS DIABETES,
CASE WHEN READ_TYPE = 'DEMENTIA'			THEN 1 ELSE 0 END AS DEMENTIA,
CASE WHEN READ_TYPE = 'LIVER_DISEASE' 		THEN 1 ELSE 0 END AS LIVER,
CASE WHEN READ_TYPE = 'HEART_FAILURE' 		THEN 1 ELSE 0 END AS HF,
CASE WHEN READ_TYPE = 'HYPERTENSION' 		THEN 1 ELSE 0 END AS HYPERTENSION,
CASE WHEN READ_TYPE = 'AF' 					THEN 1 ELSE 0 END AS AF,
CASE WHEN ra.ALF_PE IS NOT NULL 			THEN 1 ELSE 0 END AS RA,
CASE WHEN fh.ALF_PE IS NOT NULL 			THEN 1 ELSE 0 END AS FH_CVD,
CASE WHEN ckd.ALF_PE IS NOT NULL 			THEN 1 ELSE 0 END AS CKD,
smk.SMOKER AS SMOKING_STATUS
FROM MORB_SELECT A

LEFT JOIN RA       ra  ON ra.ALF_PE  = A.ALF_PE
LEFT JOIN FH_CVD   fh  ON fh.ALF_PE  = A.ALF_PE
LEFT JOIN SMOKING  smk ON smk.ALF_PE = A.ALF_PE
LEFT JOIN CKD  	   ckd ON ckd.ALF_PE = A.ALF_PE
)
GROUP BY ALF_PE
)
,

NHDL_READ AS
(
SELECT
ALF_PE,
EVENT_DT_LIPID AS TEST,
EVENT_VAL
FROM
(
SELECT 
	T.ALF_PE,
	T.EVENT_DT AS EVENT_DT_LIPID,
	T.EVENT_VAL - H.EVENT_VAL AS EVENT_VAL
FROM
(
SELECT 
	M.ALF_PE,
	GP.EVENT_DT,
	GP.EVENT_VAL
FROM ALFS M

JOIN SAILW1483V.EXTRACT_WLGP_GP_EVENT_CLEANSED GP
ON M.ALF_PE = GP.ALF_PE

JOIN SAILW1483V.PHEN_LIPID_READ D
ON GP.EVENT_CD = D.READ_CODE

WHERE GP.EVENT_DT BETWEEN FIRST_DATE - 1 YEAR AND FIRST_DATE + 30 DAYS
AND READ_TYPE = 'TC'
) T

JOIN
(
SELECT 
	M.ALF_PE,
	GP.EVENT_DT,
	GP.EVENT_VAL
FROM ALFS M

JOIN SAILW1483V.EXTRACT_WLGP_GP_EVENT_CLEANSED GP
ON M.ALF_PE = GP.ALF_PE

JOIN SAILW1483V.PHEN_LIPID_READ D
ON GP.EVENT_CD = D.READ_CODE

WHERE GP.EVENT_DT BETWEEN FIRST_DATE - 1 YEAR AND FIRST_DATE + 30 DAYS
AND READ_TYPE = 'HDL'
) H
ON T.ALF_PE = H.ALF_PE
AND T.EVENT_DT = H.EVENT_DT

UNION

SELECT 
	M.ALF_PE,
	GP.EVENT_DT AS EVENT_DT_LIPID,
	GP.EVENT_VAL
FROM ALFS M

JOIN SAILW1483V.EXTRACT_WLGP_GP_EVENT_CLEANSED GP
ON M.ALF_PE = GP.ALF_PE

JOIN SAILW1483V.PHEN_LIPID_READ D
ON GP.EVENT_CD = D.READ_CODE

WHERE GP.EVENT_DT BETWEEN FIRST_DATE - 1 YEAR AND FIRST_DATE + 30 DAYS
AND READ_TYPE = 'NON_HDL'
)
),

NHDL_WRRS AS
(
SELECT
ALF_PE,
TEST,
VAL AS EVENT_VAL
FROM
(
SELECT
	W.ALF_PE,
	SPCM_COLLECTED_DT AS TEST,
	VAL_TYPE,
	CODE,	
	NAME,	
	READ_CD,
	CAST(VAL AS DECIMAL(31,8)) AS VAL,	
	UNITOFMEASUREMENT
FROM 
	SAILW1483V.EXTRACT_WRRS_OBSERVATION_RESULT W

JOIN ALFS F
ON W.ALF_PE = F.ALF_PE
	
WHERE CODE LIKE('NHDL%')
	AND SPCM_COLLECTED_DT BETWEEN FIRST_DATE - 1 YEAR AND FIRST_DATE + 30 DAYS
	AND VAL IS NOT NULL
	AND VAL > 0
	AND VAL_TYPE = 'SN'
	AND VAL NOT IN('{redacted}','Serum Haemolysed','Not available.','NA (No sample)','NA','Insufficient sample','<0.1','NA (TEST NOT PERFORMED.)','NA (Insufficient)')
)
)
,

NHDL AS
(
SELECT
ALF_PE,
NHDL,
NHDL_VAL
FROM
(
SELECT
ALF_PE,
CASE 
	WHEN EVENT_VAL > 4.3 THEN '> 4.3'		
	WHEN EVENT_VAL <= 4.3 THEN '<= 4.3'		
END AS NHDL,
EVENT_VAL AS NHDL_VAL,
ROW_NUMBER() OVER(PARTITION BY ALF_PE ORDER BY TEST DESC) AS RANK
FROM
(
SELECT
*
FROM NHDL_WRRS

UNION

SELECT
*
FROM NHDL_READ
)
)
WHERE RANK = 1
)
,

TC_HDL AS
(
SELECT
ALF_PE,
TC_HDL
FROM
(
	SELECT
	ALF_PE,
	EVENT_VAL AS TC_HDL,
	ROW_NUMBER() OVER(PARTITION BY ALF_PE ORDER BY EVENT_DT DESC) AS RANK
	FROM
	(
		SELECT 
			T.ALF_PE,
			T.EVENT_DT,
			CAST(T.EVENT_VAL AS DECIMAL(31,8)) / CAST(H.EVENT_VAL AS DECIMAL(31,8)) AS EVENT_VAL
		FROM
		(
			SELECT 
				M.ALF_PE,
				GP.EVENT_DT,
				GP.EVENT_VAL
			FROM ALFS M
			
			JOIN SAILW1483V.EXTRACT_WLGP_GP_EVENT_CLEANSED GP
			ON M.ALF_PE = GP.ALF_PE
			
			JOIN SAILW1483V.PHEN_LIPID_READ D
			ON GP.EVENT_CD = D.READ_CODE
			
			WHERE GP.EVENT_DT BETWEEN FIRST_DATE - 1 YEAR AND FIRST_DATE + 30 DAYS
			AND READ_TYPE = 'TC'
		) T
		
		JOIN
		(
			SELECT 
				M.ALF_PE,
				GP.EVENT_DT,
				GP.EVENT_VAL
			FROM ALFS M
			
			JOIN SAILW1483V.EXTRACT_WLGP_GP_EVENT_CLEANSED GP
			ON M.ALF_PE = GP.ALF_PE
			
			JOIN SAILW1483V.PHEN_LIPID_READ D
			ON GP.EVENT_CD = D.READ_CODE
			
			WHERE GP.EVENT_DT BETWEEN FIRST_DATE - 1 YEAR AND FIRST_DATE + 30 DAYS
			AND READ_TYPE = 'HDL'
		) H
		ON T.ALF_PE = H.ALF_PE
		AND T.EVENT_DT = H.EVENT_DT
	)
)
WHERE RANK = 1
)
,

EGFR_READ AS
(
SELECT
ALF_PE,
EVENT_DT_EGFR AS TEST,
EVENT_VAL
FROM
(
SELECT
	M.ALF_PE,
	EVENT_CD,
	EVENT_DT AS EVENT_DT_EGFR,
	EVENT_VAL,
	CASE
		WHEN R.PREF_TERM_198 IS NULL AND R.PREF_TERM_60 IS NULL THEN R.PREF_TERM_30
		WHEN R.PREF_TERM_198 IS NULL THEN R.PREF_TERM_60
		ELSE PREF_TERM_198
	END AS DESC		
FROM ALFS M

JOIN SAILW1483V.EXTRACT_WLGP_GP_EVENT_CLEANSED GP
ON M.ALF_PE = GP.ALF_PE

LEFT JOIN SAILUKHDV.READ_CD_CV2_SCD R
ON GP.EVENT_CD = R.READ_CODE
	
WHERE 
	GP.EVENT_DT BETWEEN FIRST_DATE - 1 YEAR AND FIRST_DATE + 30 DAYS
	AND (R.PREF_TERM_30 LIKE('%eGFR%')
		OR R.PREF_TERM_30 LIKE('%Glom%'))
	AND EVENT_VAL IS NOT NULL
	AND EVENT_VAL > 0
)
),

EGFR_WRRS AS
(
SELECT
ALF_PE,
TEST,
VAL AS EVENT_VAL
FROM
(
SELECT
	W.ALF_PE,
	SPCM_COLLECTED_DT AS TEST,
	VAL_TYPE,
	CODE,	
	NAME,	
	READ_CD,
	CAST(
	CASE 
		WHEN VAL = '>90' THEN 91
		WHEN VAL = '>60' THEN 61
		ELSE VAL END
	AS INTEGER) AS VAL,	
	UNITOFMEASUREMENT
FROM 
	SAILW1483V.EXTRACT_WRRS_OBSERVATION_RESULT W

JOIN ALFS F
ON W.ALF_PE = F.ALF_PE
	
WHERE NAME LIKE('%GFR%')
	AND SPCM_COLLECTED_DT BETWEEN FIRST_DATE - 1 YEAR AND FIRST_DATE + 30 DAYS
	AND VAL IS NOT NULL
	AND VAL_TYPE = 'SN'
	AND VAL NOT IN('{redacted}','Serum Haemolysed','Not available.','NA (No sample)','NA','Insufficient sample','<0.1','NA (TEST NOT PERFORMED.)','NA (Insufficient)','>165','<20','Not Tested','<18','<15','Not Available','>3270.8','<13','NA (Haemolysed specimen)')
)
),

EGFR AS
(
SELECT
ALF_PE,
EGFR,
EGFR_VAL
FROM
(
SELECT
ALF_PE,
CASE 
	WHEN EVENT_VAL > 60 THEN '> 60'
	WHEN EVENT_VAL BETWEEN 30 AND 60 THEN '30 - 60'		
	WHEN EVENT_VAL < 30 THEN '< 30'		
END AS EGFR,
EVENT_VAL AS EGFR_VAL,
ROW_NUMBER() OVER(PARTITION BY ALF_PE ORDER BY TEST DESC) AS RANK
FROM
(
SELECT
*
FROM EGFR_WRRS

UNION

SELECT
*
FROM EGFR_READ
)
)
WHERE RANK = 1
)
,

LDL_READ AS
(
SELECT
ALF_PE,
FIRST_DATE,
EVENT_DT_LIPID AS TEST,
EVENT_VAL
FROM
(
SELECT 
	M.ALF_PE,
	FIRST_DATE,
	GP.EVENT_DT AS EVENT_DT_LIPID,
	GP.EVENT_VAL,
	D.READ_TYPE,
	D.READ_CODE	
FROM ALFS M

JOIN SAILW1483V.EXTRACT_WLGP_GP_EVENT_CLEANSED GP
ON M.ALF_PE = GP.ALF_PE

JOIN SAILW1483V.PHEN_LIPID_READ D
ON GP.EVENT_CD = D.READ_CODE

WHERE GP.EVENT_DT BETWEEN FIRST_DATE - 1 YEAR AND FIRST_DATE + 30 DAYS
AND READ_TYPE = 'LDL'

ORDER BY M.ALF_PE, GP.EVENT_DT
)
),

LDL_WRRS AS
(
SELECT
ALF_PE,
FIRST_DATE,
TEST,
VAL AS EVENT_VAL
FROM
(
SELECT
	W.ALF_PE,
	FIRST_DATE,
	SPCM_COLLECTED_DT AS TEST,
	VAL_TYPE,
	CODE,	
	NAME,	
	READ_CD,
	CAST(VAL AS DECIMAL(31,8)) AS VAL,	
	UNITOFMEASUREMENT
FROM 
	SAILW1483V.EXTRACT_WRRS_OBSERVATION_RESULT W

JOIN ALFS F
ON W.ALF_PE = F.ALF_PE
	
WHERE CODE LIKE('LDL%')
	AND SPCM_COLLECTED_DT BETWEEN FIRST_DATE - 1 YEAR AND FIRST_DATE + 30 DAYS
	AND VAL IS NOT NULL
	AND VAL_TYPE = 'SN'
	AND VAL NOT IN('{redacted}','Serum Haemolysed','Not available.','NA (No sample)','NA','Insufficient sample','<0.1','NA (TEST NOT PERFORMED.)','NA (Insufficient)')
)
)
,

LDL AS
(
SELECT
ALF_PE, 
TEST,
LDL, 
LDL_VAL
FROM
(
SELECT
ALF_PE,
FIRST_DATE,
CASE 
	WHEN EVENT_VAL > 3.5 THEN '> 3.5'		
	WHEN EVENT_VAL BETWEEN 2.5 AND 3.5 THEN '2.5 - 3.5'	
	WHEN EVENT_VAL < 2.5 THEN '< 2.5'		
END AS LDL,
EVENT_VAL AS LDL_VAL,
TEST,
ROW_NUMBER() OVER(PARTITION BY ALF_PE ORDER BY TEST DESC) AS RANK
FROM
(
SELECT
*
FROM LDL_WRRS

UNION

SELECT
*
FROM LDL_READ
)
)
WHERE RANK = 1
)
,

ALF_LDL_COMB AS
(
SELECT
ALF_PE,
CASE WHEN L.ALF_PE IS NOT NULL THEN TEST ELSE A.FIRST_DATE END AS DT
FROM ALFS A

LEFT JOIN LDL L
USING (ALF_PE)
)
--SELECT COUNT(DISTINCT ALF_PE) FROM ALF_LDL_COMB
,

SBP AS
(
SELECT
ALF_PE,
SBP
FROM
(
SELECT
B.ALF_PE,
EVENT_DT,
CASE WHEN SYS = 999 OR SYS = -999 THEN NULL ELSE SYS END AS SBP,
ROW_NUMBER() OVER(PARTITION BY B.ALF_PE ORDER BY EVENT_DT DESC) AS RANK
FROM ALFS A

JOIN SAILW1483V.ASCVD_BLOOD_PRESSURES B
ON A.ALF_PE = B.ALF_PE

WHERE B.EVENT_DT BETWEEN A.FIRST_DATE - 1 YEARS AND A.FIRST_DATE + 30 DAYS
)
WHERE RANK = 1
)
,

LLT AS
(
SELECT
ALF_PE,
CASE 
	WHEN INEGY = 1 THEN 4
	WHEN (HI_STAT = 1 OR LI_STAT = 1) AND EZET_FIBR = 1 THEN 4
	WHEN HI_STAT = 1 AND LI_STAT = 1 THEN 3
	WHEN HI_STAT = 1 THEN 3		
	WHEN LI_STAT = 1 THEN 2	
	WHEN EZET_FIBR = 1 THEN 1
	ELSE 0
END AS LLT_INT,
CASE 
	WHEN INEGY = 1 OR HI_STAT = 1 OR LI_STAT = 1 THEN 1
	ELSE 0
END AS STATIN
FROM
(
SELECT
ALF_PE,
MAX(HI_STAT) AS HI_STAT,
MAX(LI_STAT) AS LI_STAT,
MAX(INEGY) AS INEGY,
MAX(EZET_FIBR) AS EZET_FIBR
FROM 
(
SELECT
A.ALF_PE,
CASE WHEN READ_TYPE = 'HIGH_STATIN' 						THEN '1' ELSE '0' END AS HI_STAT,
CASE WHEN READ_TYPE = 'LOW_STATIN' 							THEN '1' ELSE '0' END AS LI_STAT,
CASE WHEN READ_TYPE = 'INEGY' 								THEN '1' ELSE '0' END AS INEGY,
CASE WHEN READ_TYPE = 'EZETIMIBE' OR READ_TYPE = 'FIBRATE'	THEN '1' ELSE '0' END AS EZET_FIBR
FROM ALF_LDL_COMB A

JOIN SAILW1483V.EXTRACT_WLGP_GP_EVENT_CLEANSED GP
ON A.ALF_PE = GP.ALF_PE

JOIN SAILW1483V.PHEN_DRUG_READ D
ON GP.EVENT_CD = D.READ_CODE

WHERE EVENT_DT BETWEEN DT - 60 DAYS AND DT
AND READ_TYPE IN('HIGH_STATIN', 'LOW_STATIN', 'INEGY', 'EZETIMIBE', 'FIBRATE')
)
GROUP BY ALF_PE
)
)
,

ANTI_HTN_1 AS 
(
SELECT
GP.ALF_PE,
CASE WHEN L.ANTIHYPERTENSIVE_CLASS LIKE 'CENTRAL' THEN 'X'
WHEN L.ANTIHYPERTENSIVE_CLASS LIKE 'ALFA' THEN 'L'
ELSE L.ANTIHYPERTENSIVE_CLASS END AS DRUG_CLASS
FROM ALFS A

JOIN SAILW1483V.EXTRACT_WLGP_GP_EVENT_CLEANSED GP
ON A.ALF_PE = GP.ALF_PE

JOIN SAILW1483V.HYPERTENSIVE_DRUGS L
ON GP.EVENT_CD = L.READ_CODE

WHERE EVENT_DT BETWEEN FIRST_DATE - 60 DAYS AND FIRST_DATE
)
,

ANTI_HTN_2 AS 
(
SELECT 
ALF_PE,
MAX(CASE WHEN DRUG_CLASS LIKE '%A%' THEN 1 ELSE 0 END) AS DRUG_A,
MAX(CASE WHEN DRUG_CLASS LIKE '%B%' THEN 1 ELSE 0 END) AS DRUG_B,
MAX(CASE WHEN DRUG_CLASS LIKE '%C%' THEN 1 ELSE 0 END) AS DRUG_C,
MAX(CASE WHEN DRUG_CLASS LIKE '%D%' THEN 1 ELSE 0 END) AS DRUG_D,
MAX(CASE WHEN DRUG_CLASS LIKE '%K%' THEN 1 ELSE 0 END) AS DRUG_K,
MAX(CASE WHEN DRUG_CLASS LIKE '%L%' THEN 1 ELSE 0 END) AS DRUG_ALFA,
MAX(CASE WHEN DRUG_CLASS LIKE '%V%' THEN 1 ELSE 0 END) AS DRUG_V,
MAX(CASE WHEN DRUG_CLASS LIKE '%X%' THEN 1 ELSE 0 END) AS DRUG_Central
FROM ANTI_HTN_1

GROUP BY ALF_PE
)
,

ANTI_HTN AS
(
SELECT
ALF_PE,
CASE WHEN CLASSES >= 4 THEN 4 ELSE CLASSES END AS AHT_INT,
CASE WHEN CLASSES >= 1 THEN 1 ELSE 0 END AS AHT
FROM
(
SELECT 
A.ALF_PE,
CASE WHEN P.ALF_PE IS NOT NULL THEN (DRUG_A + DRUG_B + DRUG_C + DRUG_D + DRUG_K + DRUG_ALFA + DRUG_V + DRUG_Central) 
ELSE 0 END AS CLASSES 
FROM ALFS A

LEFT JOIN ANTI_HTN_2 P
USING(ALF_PE)
)
)

SELECT 
	M.ALF_PE, 
	M.FIRST_DATE AS DIAG_DT,
	M.CENSOR_DATE AS CNS_DT,
	'ASCVD' AS COHORT,
	G.LSOA2011_CD AS LSOA,
	G.MSOA_CD AS MSOA,
	G.LAD_CD AS LAD,
	CASE WHEN H.ALF_PE IS NOT NULL THEN 1 ELSE 0 END AS HE,
	CASE 
	WHEN M.GENDER = 1 THEN 'M'
	WHEN M.GENDER = 2 THEN 'F'
	ELSE NULL END AS SEX, 
	G.WIMD_2019_QUINTILE AS WIMD, 
	td.tds AS TOWNSEND,
    COALESCE(M.ETHNICITY, 'Unknown')    AS ETHN,
	M.AGE_DIAG AS AGE, 
	CASE WHEN M.TYPE = 'ST' THEN 'Stroke' ELSE M.TYPE END AS TYPE, 
	SMK,
	M.BMI,
	CASE WHEN DM IS NULL THEN 0 ELSE DM END AS DM, 
	CASE WHEN DMTA IS NULL THEN 0 ELSE DMTA END AS DMTA, 
	CASE WHEN LVR IS NULL THEN 0 ELSE LVR END AS LVR, 
	CASE WHEN HTN IS NULL THEN 0 ELSE HTN END AS HTN, 
	CASE WHEN HF IS NULL THEN 0 ELSE HF END AS HF,
	CASE WHEN AF IS NULL THEN 0 ELSE AF END AS AF,	
	CASE WHEN RA IS NULL THEN 0 ELSE RA END AS RA,
	CASE WHEN FH_CVD IS NULL THEN 0 ELSE FH_CVD END AS FH_CVD,	
	CASE WHEN X.CKD IS NULL THEN 0 ELSE X.CKD END AS CKD,		
	CASE WHEN LLT_INT IS NULL THEN 0 ELSE LLT_INT END AS LLT_INT,
	CASE WHEN STATIN IS NULL THEN 0 ELSE STATIN END AS STATIN,	
	CASE WHEN AHT_INT IS NULL THEN 0 ELSE AHT_INT END AS AHT_INT,	
	CASE WHEN AHT IS NULL THEN 0 ELSE AHT END AS AHT,
	LDL,
	LDL_VAL,	
	NHDL,
	NHDL_VAL,
	TC_HDL,
	EGFR,
	EGFR_VAL,
	SBP AS SBP_VAL
FROM SAILW1483V.COHORT_MASTER_FINAL M

JOIN ALFS A
USING(ALF_PE)

LEFT JOIN MORB_MAX X
USING(ALF_PE)

LEFT JOIN 
(
SELECT DISTINCT ALF_PE FROM SAILW1483V.P3_ASCVD_HARD_EVENTS_CLASS
WHERE EVENT_DT BETWEEN FIRST_DATE AND FIRST_DATE + 7
AND CLASS = 'MACE'
) H
USING(ALF_PE)

LEFT JOIN 
(
SELECT
L.*,
MSOA11CD AS MSOA_CD,
LAD11CD AS LAD_CD
FROM
(
SELECT 
W.*,
ROW_NUMBER() OVER(PARTITION BY W.ALF_PE ORDER BY START_DATE DESC) AS RANK
FROM SAILW1483V.EXTRACT_WDSD_SINGLE_CLEAN_GEO_CHAR_LSOA2011  W

JOIN SAILW1483V.COHORT_MASTER_FINAL M
USING(ALF_PE)

WHERE 
LSOA2011_CD <> 'N/A' 
AND ((M.FIRST_DATE BETWEEN START_DATE AND END_DATE) 
	OR (M.FIRST_DATE < START_DATE AND END_DATE = '9999-01-01'))
) L

JOIN (SELECT LSOA11CD, MSOA11CD, LAD11CD FROM SAILW1483V.LSOA_MSOA_LAD_ENGLAND_WALES WHERE LSOA11CD LIKE ('W%') GROUP BY LSOA11CD, MSOA11CD, LAD11CD) W
ON LSOA2011_CD = LSOA11CD

WHERE RANK = 1
) G
USING(ALF_PE)

LEFT JOIN EGFR E
USING (ALF_PE)

LEFT JOIN NHDL N
USING (ALF_PE)

LEFT JOIN LDL L
USING (ALF_PE)

LEFT JOIN SBP S
USING (ALF_PE)

LEFT JOIN TC_HDL
USING (ALF_PE)

LEFT JOIN LLT
USING (ALF_PE)

LEFT JOIN ANTI_HTN
USING (ALF_PE)

LEFT JOIN SAILW1483V.TOWNS_DEP_SCORE td 
ON td.GEO_CODE = G.LSOA2011_CD

WHERE M.AGE_DIAG BETWEEN 25 AND 84
; 
COMMIT;
--
------------------------------------------
--
-- Select all results
SELECT 
*
FROM 
	SAILW1483V.CAPSTONE_ASCVD_RISK_CALCULATION;
--
-- Count all results
SELECT 
	COUNT(*)
FROM 
	SAILW1483V.CAPSTONE_ASCVD_RISK_CALCULATION;
	
SELECT 
	COUNT(DISTINCT ALF_PE)
FROM 
	SAILW1483V.CAPSTONE_ASCVD_RISK_CALCULATION;

------------------------------------------
--
--Drop Table
CALL FNC.DROP_IF_EXISTS('SAILW1483V.CAPSTONE_RISK_CALCULATION_COHORT');
COMMIT;
------------------------------------------ 
--
-- Create Table
CREATE TABLE SAILW1483V.CAPSTONE_RISK_CALCULATION_COHORT
(
	ALF_PE			BIGINT,
	DIAG_DT			DATE,
	CNS_DT			DATE,
	COHORT			VARCHAR(10),
	LSOA			VARCHAR(10),
	MSOA			VARCHAR(10),
	LAD				VARCHAR(10),
	HE				INTEGER,
	SEX				VARCHAR(1),
	WIMD			INTEGER,
	TOWNSEND		DECIMAL(31,8),
	ETHN			VARCHAR(10),
	AGE				INTEGER,
	TYPE			VARCHAR(10),
	SMK				VARCHAR(10),
	BMI				DECIMAL(31,8),
	DM				INTEGER,
	DMTA			INTEGER,
	LVR				INTEGER,
	HTN				INTEGER,
	HF				INTEGER,
	AF				INTEGER,
	RA				INTEGER,
	FH_CVD			INTEGER,
	CKD				INTEGER,
	LLT_INT			INTEGER,
	STATIN			INTEGER,	
	AHT_INT			INTEGER,
	AHT				INTEGER,	
	LDL				VARCHAR(10),
	LDL_VAL			DECIMAL(31,8),
	NHDL			VARCHAR(10),	
	NHDL_VAL		DECIMAL(31,8),
	TC_HDL			DECIMAL(31,8),	
	EGFR			VARCHAR(10),	
	EGFR_VAL		DECIMAL(31,8),
	SBP_VAL			DECIMAL(31,8)
) 
;
COMMIT;
------------------------------------------
--
--Insert into Table
INSERT INTO SAILW1483V.CAPSTONE_RISK_CALCULATION_COHORT
--
SELECT * FROM SAILW1483V.CAPSTONE_ASCVD_RISK_CALCULATION

UNION ALL

SELECT * FROM SAILW1483V.CAPSTONE_DM_RISK_CALCULATION
; 
COMMIT;
--
------------------------------------------
--
-- Select all results
SELECT 
*
FROM 
	SAILW1483V.CAPSTONE_RISK_CALCULATION_COHORT;
--
-- Count all results
SELECT 
	COUNT(*)
FROM 
	SAILW1483V.CAPSTONE_RISK_CALCULATION_COHORT;
	
SELECT 
	COUNT(DISTINCT ALF_PE)
FROM 
	SAILW1483V.CAPSTONE_RISK_CALCULATION_COHORT;
